### ISSUE TITLE
Are there any contributing guidelines ?

### ISSUE THREAD

**Issue by Bavragor** [doctrine/search#114]
I would like to contribute to that project, because I'm looking forward that this will become more than a prototype.
Anything else todo besides the @todo things ?

Greetings :)

**Comment by MrHash** [comment]
Hello, have you been using the package already? Coding guidelines are the same for all Doctrine org projects (i.e. PSR-2) and some of the outstanding issues are listed in the issues.

Have you come across any features that your need?
