### ISSUE TITLE
Status updates?

### ISSUE THREAD

**Issue by EmanueleMinotto** [doctrine/search#116]
@MrHash I'm seeing that you're working in the _develop_ branch and some issues like https://github.com/doctrine/search/issues/68 are completed there, so what's the current status of this project (I mean: which issues are still to do)?

**Comment by MrHash** [comment]
Hello yes i haven't worked on it for a while but some of these features are done. I haven't setup proper branches for versions yet so any feedback is appreciated. Probably the most important thing is #85 but it requires some in depth understanding of how things are working. Have you been using the package much?

**Comment by EmanueleMinotto** [comment]
No, not yet, I'm starting to discover how this project is working.
Anyway I usually send PRs while discovering things, that's why I'm asking.

**Comment by MrHash** [comment]
Right well unforunately there aren't proper tests yet so that make it difficult to ensure quality at the moment. That's another important thing to do!
