### ISSUE TITLE
The annotation does not exist, or could not be auto-loaded.

### ISSUE THREAD

**Issue by clovis818** [doctrine/search#120]
[Semantical Error] The annotation \"@Doctrine\\Search\\Mapping\\Annotations\\ElasticSearchable\" in class app\\models\\TestModel does not exist, or could not be auto-loaded.

I'm trying to test this library with a working Doctrine Model.

Seems like you don't support SimpleAnnotationReader but I have tried to use the AnnotationReader.
@ORM\Entity but that still does not work.

**Comment by MrHash** [comment]
HI there is a working demo you can play with at https://github.com/doctrine/search/tree/master/demo and there is a `develop` branch with more features at the moment.
